export const RECIPE_LIST_REQUEST = 'RECIPE_LIST_REQUEST'
export const RECIPE_LIST_SUCCESS = 'RECIPE_LIST_SUCCESS'
export const RECIPE_LIST_FAIL = 'RECIPE_LIST_FAIL'

export const RECIPE_LIST_DETAILS_REQUEST = 'RECIPE_LIST_DETAILS_REQUEST'
export const RECIPE_LIST_DETAILS_SUCCESS = 'RECIPE_LIST_DETAILS_SUCCESS'
export const RECIPE_LIST_DETAILS_FAIL = 'RECIPE_LIST_DETAILS_FAIL'
export const RECIPE_LIST_DETAILS_RESET = 'RECIPE_LIST_DETAILS_RESET'

export const RECIPE_REVIEW_CREATE_REQUEST = 'RECIPE_REVIEW_CREATE_REQUEST'
export const RECIPE_REVIEW_CREATE_SUCCESS = 'RECIPE_REVIEW_CREATE_SUCCESS'
export const RECIPE_REVIEW_CREATE_FAIL = 'RECIPE_REVIEW_CREATE_FAIL'
export const RECIPE_REVIEW_CREATE_RESET = 'RECIPE_REVIEW_CREATE_RESET'

export const RECIPE_REVIEW_EDIT_REQUEST = 'RECIPE_REVIEW_EDIT_REQUEST'
export const RECIPE_REVIEW_EDIT_SUCCESS = 'RECIPE_REVIEW_EDIT_SUCCESS'
export const RECIPE_REVIEW_EDIT_FAIL = 'RECIPE_REVIEW_EDIT_FAIL'
export const RECIPE_REVIEW_EDIT_RESET = 'RECIPE_REVIEW_EDIT_RESET'

export const RECIPE_REVIEW_DELETE_REQUEST = 'RECIPE_REVIEW_DELETE_REQUEST'
export const RECIPE_REVIEW_DELETE_SUCCESS = 'RECIPE_REVIEW_DELETE_SUCCESS'
export const RECIPE_REVIEW_DELETE_FAIL = 'RECIPE_REVIEW_DELETE_FAIL'
export const RECIPE_REVIEW_DELETE_RESET = 'RECIPE_REVIEW_DELETE_RESET'

export const RECIPE_FAVORITES_ADD_REQUEST = 'RECIPE_FAVORITES_ADD_REQUEST'
export const RECIPE_FAVORITES_ADD_SUCCESS = 'RECIPE_FAVORITES_ADD_SUCCESS'
export const RECIPE_FAVORITES_ADD_FAIL = 'RECIPE_FAVORITES_ADD_FAIL'
export const RECIPE_FAVORITES_ADD_RESET = 'RECIPE_FAVORITES_ADD_RESET'
